name: SwiftLint

on:
  push:
    branches: [ "main", "develop", "release/0.1", "release/0.2", "release/0.3"]
  pull_request:
    branches: [ "main", "develop", "release/0.1", "release/0.2", "release/0.3"]

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ejecutar SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1